# Generated by Django 3.1.7 on 2021-03-29 11:52

from django.db import migrations, models
import webapp.ValidationError


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210318_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[webapp.ValidationError.MinLengthValidator(5)], verbose_name='Текст')),
                ('description', models.TextField(max_length=2000, validators=[webapp.ValidationError.RegexValidator(['zzz', 'xxx', 'ccc', 'vvv'])], verbose_name='Поле')),
                ('created_at', models.DateField(verbose_name='Время создания')),
                ('updated_at', models.DateField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, validators=[webapp.ValidationError.MinLengthValidator(5)], verbose_name='Текст'),
        ),
    ]
